apiVersion: v1
kind: Service
metadata:
  labels:
    app: fusion-backend
  name: fusion-backend
  namespace: iff-backend
spec:
  ports:
  - port: 8080
  selector:
    app: fusion-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: fusion-backend
  namespace: iff-backend
  labels:
    app: fusion-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fusion-backend
    spec:
      containers:
      - name: fusion-backend
        image: k3d-iff.localhost:12345/iff/fusionbackend:latest
        ports:
        - containerPort: 8080
#        command: ["sleep"]
#        args: ["10000"]
        volumeMounts:
        - name: application-config 
          mountPath: "/app/resources/config/" 
          readOnly: true
      imagePullSecrets:
      - name: dockercred
      
      volumes:
        - name: application-config
          configMap:
            name: backend-config 
            items:
            - key: application.yaml 
              path: application.yaml
